### PR TITLE
[WIP] Added watchtower scripts

### PR DESCRIPTION
**Pull request by NelleV**
This PR is work in progress on generating automatically a bunch of plots and pages for our projects and users.

### CODE REVIEW

**Comment by choldgraf** [comment]
for downloading the CSV automatically, it should work if we host it on dropbox. I wrote this function that should work: https://github.com/data-8/connector-instructors/blob/gh-pages/connectortools/utils.py#L47

it will take a Dropbox link and download the file for you. Want to either use connectortools or port over that code to `src` for the docathon? I don't know that it's possible to do this using google drive in an easy way (you'd need to embed the authentication info into travis)

**Comment by choldgraf** [comment]
we can use this url: https://www.dropbox.com/s/0xendp6g404ntzh/Docathon%20Project%20registration%20%28Responses%29%20-%20Form%20Responses%201.csv?dl=0

**Comment by Carreau** [comment]
it won't work on a PR you have to merge it for the secret to be decrypted. 
That's becausee otherwise someone could just send a PR with `echo $SECRET`

Unless you made encrypted it with NelleV/docathon fork, in which case it will work on your travis, but not here.

**Comment by Carreau** [comment]
```
Traceback (most recent call last):
  File "plot_commits.py", line 96, in <module>
    groupby=groupby, since=since)
  File "plot_commits.py", line 56, in plot_commits
    fig, ax = plt.subplots(figsize=(8, 4))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/matplotlib/pyplot.py", line 1203, in subplots
    fig = figure(**fig_kw)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/python/3.5.2/lib/python3.5/tkinter/__init__.py", line 1868, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by choldgraf** [comment]
I am thinking I'll just merge this, and then get the pages building manually offline, then we can open a separate PR to get travis building the docs. does that work?

**Comment by Carreau** [comment]
> I am thinking I'll just merge this, and then get the pages building manually offline, then we can open a separate PR to get travis building the docs. does that work?

I'm working on it, give me 30 min

**Comment by choldgraf** [comment]
are you forking this branch?

**Comment by Carreau** [comment]
> are you forking this branch?

Yes, I'm working on `<this repository>/54`,  which does decrypt the env variable. Just fixing some extra bugs. then I'll submit an alternative to this PR.

**Pull request merged**
