### PR TITLE
Add eScience as a host location

### PR DESCRIPTION
**Pull request by arokem**
Please don't merge yet. Waiting on confirmation of some of the details (e.g., are we live-streaming BIDS tutorials?) from @jakevdp.

### CODE REVIEW

**Comment by choldgraf** [comment]
We can probably set up some kind of live-streaming for tutorials, if that'd be useful :)

Anything you guys would like to speak about as well? See a tentative list of tutorials in #26.

And feel free to spread the message far and wide as well :)

**Comment by arokem** [comment]
OK. Here goes!

**Comment by choldgraf** [comment]
(LMK when it's ready for a merge!)

**Comment by arokem** [comment]
I think it's read now.

**Comment by choldgraf** [comment]
assume you mean `ready` :)  merging!

**Pull request merged**
