### PR TITLE
Intitial GC page

### PR DESCRIPTION
**Pull request by story645**
I still need to get some details and an eventbrite page and fill in those blanks.

### CODE REVIEW

**Comment by choldgraf** [comment]
Looks good! When you're ready for a merge post a comment here!

**Comment by choldgraf** [comment]
Any updates on this? LMK if you want me to take a look!

**Comment by story645** [comment]
Just updated with the eventbrite link, so ready to go

**Comment by Carreau** [comment]
Merged ! Should be deployed in a few minutes.

**Pull request merged**
