### PR TITLE
Build using travis

### PR DESCRIPTION
**Pull request by Carreau**
This does not yet autodeploy though.

### CODE REVIEW

**Comment by Carreau** [comment]
I'm going to merge this, just to see if it deploy on my fork. we can revert if needed later. 

I need that to be in master because travis only decrypt secrets (here one SSH key) only if it's on master.

**Comment by Carreau** [comment]
Well, travis is not enabled,  I can't enable it. Can someone with right do it ?

**Comment by Carreau** [comment]
like @NelleV ?

**Comment by choldgraf** [comment]
ah I see this is the travis issue, ok I'll close the other one

**Comment by Carreau** [comment]
Or you can give me more right on the repo and I can enable travis myself.

**Comment by choldgraf** [comment]
I didn't already do that? you have edit privileges...lemme try to make you an admin

**Comment by choldgraf** [comment]
done
--

**Comment by Carreau** [comment]
Sweet ! Thanks !

**Comment by Carreau** [comment]
dealwithitparrot

**Comment by NelleV** [comment]
My eyes are bleeding…

**Pull request merged**
