### PR TITLE
Switch publication of blog to this repo.

### PR DESCRIPTION
**Pull request by Carreau**
This (should) switch the publication of the blog to the gh-pages branch
of _this_ repo.

It also remove the ssh key that allows to upload to my fork and replace
it for an ssh key that can push to this repo.

The key can be revoked at anytime and should is used only for this
operation.

### CODE REVIEW

**Comment by choldgraf** [comment]
so this will auto-build the website when we push new commits to master?

**Comment by choldgraf** [comment]
(btw, sorry I hadn't set up PR/issue notifications yet so I missed this)

**Comment by Carreau** [comment]
> so this will auto-build the website when we push new commits to master?

In theory it should. 

Currently it autodeploy [there](https://carreau.github.io/docathon/), and that's just switching the destination. If it does not I'll debug quickly.

**Comment by choldgraf** [comment]
ok I'm going to blindly merge this because I'm not sure how exactly it works, but I trust you and I think @NelleV won't have time to review for a little bit. However I'd love for you to explain this to me sometime soon :)

**Comment by Carreau** [comment]
> ok I'm going to blindly merge this because I'm not sure how exactly it works,

I just created an SSH key on put the public-facing part one on GitHub, and the private part is coomitted to this repo and decrypted by travis when building master.

it's just a matter of now running `make html` on travis, committing and pushing.

> @NelleV won't have time to review for a little bit.

It seem it does not build the markdown files though... wondering if it is an intermittent bug as it did build them on my fork on `markdown` is installed.

**Comment by Carreau** [comment]
> It seem it does not build the markdown files though... wondering if it is an intermittent bug as it did build them on my fork on markdown is installed.

Ok, it's fixed. Pelican 3.7 is broken and  does not add the link to the markdown files in the header. 
I pined Pelican to <3.7 and pushed directly on master.

**Comment by choldgraf** [comment]
awesome - thanks for solving the pelican problem. Can you run me through how this setup works via skype? I think it might be useful to cover as a topic during the docathon.

**Comment by Carreau** [comment]
sure, if you are here monday/tuesday we can even find a time to discuss this.

**Comment by choldgraf** [comment]
I might be around tomorrow, but still unclear as I might need to be in SF to record data from a patient. Will you generally be around BIDS? I can let you know as soon as I find out my timing.

**Comment by Carreau** [comment]
> I might be around tomorrow, but still unclear as I might need to be in SF to record data from a patient. Will you generally be around BIDS? I can let you know as soon as I find out my timing.

Might be at LBL for a bit, but we can figure things out.

**Comment by choldgraf** [comment]
cool - would morning or afternoon work better for you? I can be there for one of those but prob not both.

**Comment by Carreau** [comment]
Afternoon likely a bit better, I have an 11 to 12:30 meeting at LBNL. Tell me when and I'll be there.

**Comment by choldgraf** [comment]
Sounds good - I'll need to leave pretty quickly after that...I'm in BIDS now. If you don't think you can make it by 1:00pm, then let's just meet over skype, ok?

**Comment by Carreau** [comment]
> Sounds good - I'll need to leave pretty quickly after that...I'm in BIDS now. If you don't think you can make it by 1:00pm, then let's just meet over skype, ok?

I won't make it by 1. Let's skype later.

**Pull request merged**
