### PR TITLE
ENH started a blog/website

### PR DESCRIPTION
**Pull request by NelleV**
Here is the website that I have started.
@choldgraf don't hesitate to tell me whether I should do a better job of documenting before merging.

### CODE REVIEW

**Comment by choldgraf** [comment]
Looks good for a first merge - I see that a lot of pages are written in HTML...is the plan to edit these directly or is there some kind of markdown / rST -> HTML pipeline with pelican? I've only used it a little bit.

**Comment by choldgraf** [comment]
(also I know this isn't related to this PR, but I created a project board for this in case it'd be useful)

**Comment by NelleV** [comment]
So I copy pasted an existing themes, and I think a lot of the html files are actually templates.
Most of the pages should be written in rst, but we can see page by page.

**Comment by NelleV** [comment]
I never merge my own PR so merge when you feel it is ready :D

**Pull request merged**
